workflows:
  ios-native:
    environment:
      vars:
        BUNDLE_ID: "com.avinash.Velocity"
        XCODE_PROJECT: "Velocity.xcodeproj" # <-- Name of your Xcode project
        XCODE_SCHEME: "Velocity" # <-- Name of your Xcode scheme
    scripts:
      # ...
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
